name: Päivitä ruokalista

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Hae ruokalistan data
        run: |
          DATE=$(date +%Y-%m-%d)
          URL="https://api.fi.poweresta.com/publicmenu/dates/muhosutajarvivaala/muhoskoulut/?menu=ruokalista&dates=$DATE"
          curl -o menu.json "$URL"

      - name: Luo konfiguraatio (config.js)
        run: |
          echo "const CONFIG = { API_KEY: '${{ secrets.GEMINI_API_KEY }}' };" > config.js

      - name: Commit ja Push muutokset
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # -f pakottaa lisäämään config.js tiedoston, vaikka se olisi .gitignore-listalla
          git add -f menu.json config.js
          git commit -m "Robotti päivitti ruokalistan ja konfiguraation" || exit 0
          git push
