name: Päivitä ruokalista

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Hae ruokalistan data
        run: |
          DATE=$(date +%Y-%m-%d)
          URL="https://api.fi.poweresta.com/publicmenu/dates/muhosutajarvivaala/muhoskoulut/?menu=ruokalista&dates=$DATE"
          curl -o menu.json "$URL"

      - name: Luo konfiguraatio
        run: |
          echo "const CONFIG = { API_KEY: '${{ secrets.GEMINI_API_KEY }}' };" > config.js

      - name: Pakota päivitys Gittiin
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Pakotetaan config.js mukaan vaikka .gitignore kieltäisi
          git add -f menu.json config.js
          git commit -m "Robotti päivitti tiedostot" || exit 0
          git push
